### ISSUE TITLE
Module not found: Recursion in resolving

### ISSUE THREAD

**Issue by Hawerrr** [webistomin/nanogram.js#14]
**Describe the bug**
for fix need replace all `dist/` to `./dist/` in `package.json`

Sorry i cant make PR

**Screenshots**
![Screenshot from 2020-05-21 10-09-41](https://user-images.githubusercontent.com/19683674/82538137-8d146d00-9b4b-11ea-80e4-cdae69e5884a.png)
![Screenshot from 2020-05-21 10-09-34](https://user-images.githubusercontent.com/19683674/82538142-8dad0380-9b4b-11ea-8006-d390a6413387.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome
 - Version: 79

**Comment by webistomin** [comment]
> **Describe the bug**
> for fix need replace all `dist/` to `./dist/` in `package.json`
> 
> Sorry i cant make PR
> 
> **Screenshots**
> ![Screenshot from 2020-05-21 10-09-41](https://user-images.githubusercontent.com/19683674/82538137-8d146d00-9b4b-11ea-80e4-cdae69e5884a.png)
> ![Screenshot from 2020-05-21 10-09-34](https://user-images.githubusercontent.com/19683674/82538142-8dad0380-9b4b-11ea-8006-d390a6413387.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: linux
> * Browser: chrome
> * Version: 79

Hi! Check this PR https://github.com/webistomin/nanogram.js/pull/15

Also try to install this version. I hope this helps, but please let me know if you need anything else or if you have any other questions
```bash
npm i nanogram.js@1.0.2-beta.1
```

**Comment by Hawerrr** [comment]
thanks!

**Comment by Hawerrr** [comment]
its working! perfect. thanks
