### ISSUE TITLE
TypeError: i.ProfilePage is undefined

### ISSUE THREAD

**Issue by gergelyppp** [webistomin/nanogram.js#228]
Hello @webistomin, I've got the same error on every websites where I use this library 😕 

_Firefox 82.0.3 (64 bit)_

<img width="1608" src="https://user-images.githubusercontent.com/61058110/99699847-bbd7b580-2a92-11eb-80f6-ad0c9a05519d.png">

_Safari 14.0.1 (16610.2.11.51.8)_

<img width="1608" src="https://user-images.githubusercontent.com/61058110/99700779-e8400180-2a93-11eb-858c-1670e2dc9971.png">

**Comment by webistomin** [comment]
Hello, @gergelyppp 😉

Can you give me your instagram username to debug?

**Comment by gergelyppp** [comment]
Yes sure, such as this: **lifeguard.design**

It seems that it worked well for a short time yesterday, but today I realised that it doesn't work at all - the demo page also doesn't work either: https://nanogram-js.now.sh

(the error message is the same as it was earlier)

**Comment by webistomin** [comment]
> Yes sure, such as this: **lifeguard.design**
> 
> It seems that it worked well for a short time yesterday, but today I realised that it doesn't work at all - the demo page also doesn't work either: https://nanogram-js.now.sh
> 
> (the error message is the same as it was earlier)

It looks like your network has been temporary banned because of too many requests.

Take a look at the caveats section

https://github.com/webistomin/nanogram.js#caveats-

**Comment by yusufkhan07** [comment]
@webistomin Can you add a more descriptive error instead of giving undefined?

**Comment by webistomin** [comment]
> @webistomin Can you add a more descriptive error instead of giving undefined?

Yeah, I'll find the time to refactor
