### ISSUE TITLE
Not working image parse

### ISSUE THREAD

**Issue by etozhealkhipce** [webistomin/nanogram.js#232]
![image](https://user-images.githubusercontent.com/38625168/99874304-ff582e00-2c10-11eb-9226-1227f2e6155d.png)
Link: https://nanogram-js.now.sh/

**Comment by webistomin** [comment]
Hi! Take a look at caveats section

https://github.com/webistomin/nanogram.js#caveats-

Perhaps you are banned

**Comment by etozhealkhipce** [comment]
> Hi! Take a look at caveats section
> 
> https://github.com/webistomin/nanogram.js#caveats-
> 
> Perhaps you are banned

You're right, thanks

**Comment by webistomin** [comment]
> > Hi! Take a look at caveats section
> > https://github.com/webistomin/nanogram.js#caveats-
> > Perhaps you are banned
> 
> You're right, thanks

Can you tell me how much times you reload your page and make request?
