### ISSUE TITLE
Profile picture

### ISSUE THREAD

**Issue by iieternal** [webistomin/nanogram.js#249]
Is there a way to get my profile picture with nanogram.js

**Comment by webistomin** [comment]
> Is there a way to get my profile picture with nanogram.js

```js
import Nanogram from 'nanogram.js';

const instagramParser = new Nanogram();

instagramParser.getMediaByUsername('instagram').then((media) => {
  const profilePic = media.profile_pic_url_hd
});
```

**Comment by iieternal** [comment]
Thank you ✌️

**Comment by iieternal** [comment]
media.profile.profile_pic_url_hd

This worked better for me.

**Comment by webistomin** [comment]
> media.profile.profile_pic_url_hd
> 
> This worked better for me.

yeah, sorry
