### ISSUE TITLE
how to get next page?

### ISSUE THREAD

**Issue by sajjad-ser** [webistomin/nanogram.js#3]
**Is your feature request related to a problem? Please describe.**
hot to get next page?

**Describe the solution you'd like**
i want to get next page of user media only 12 item returned by ```getMediaByUsername```

**Describe alternatives you've considered**
n/p
**Additional context**
n/p

**Comment by webistomin** [comment]
> **Is your feature request related to a problem? Please describe.**
> hot to get next page?
> 
> **Describe the solution you'd like**
> i want to get next page of user media only 12 item returned by `getMediaByUsername`
> 
> **Describe alternatives you've considered**
> n/p
> **Additional context**
> n/p

Hi!✌

12 photos is the maximum for this method. I think there is no way to load more content.
Use [instafeed.js](https://github.com/stevenschobert/instafeed.js) with `access_token` to load more items.
