### ISSUE TITLE
Plugin stopped working overnight

### ISSUE THREAD

**Issue by ViniDB27** [webistomin/nanogram.js#304]
Good morning, how are you? hope so!
We used this library in some projects, and it has satisfied us very well, but it has been a few days since the plugin is simply not working anymore, we have the habit of using it by CDN, I noticed that 5 days ago there was an update, possibly it reason for stopping the plugin in our projects, was there a big change in the last update?
Thanks in advance for your attention.

**Comment by webistomin** [comment]
> Good morning, how are you? hope so!
> We used this library in some projects, and it has satisfied us very well, but it has been a few days since the plugin is simply not working anymore, we have the habit of using it by CDN, I noticed that 5 days ago there was an update, possibly it reason for stopping the plugin in our projects, was there a big change in the last update?
> Thanks in advance for your attention.

Hi! Yeah, this library was completely rewritten for a better tree-shaking and smaller size. Now it is a bunch of pure functions instead of class.

You can use the old version. 
https://cdn.jsdelivr.net/npm/nanogram.js@2.0.2/dist/nanogram.iife.min.js

**Comment by ViniDB27** [comment]
Show, thanks for the help
