### ISSUE TITLE
Reel Download

### ISSUE THREAD

**Issue by Hax4us** [webistomin/nanogram.js#319]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Can you add support to download  instagram Reels

**Comment by webistomin** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Can you add support to download instagram Reels

The link looks like this?

```js
https://www.instagram.com/stories/highlights/<YOUR_REEL_ID>/
```

**Comment by Hax4us** [comment]
link looks like
`https://www.instagram.com/reel/CKONdDkJaPU/?igshid=us91qcp3a97l`

**Comment by webistomin** [comment]
> link looks like
> 
> ```
> https://www.instagram.com/reel/CKONdDkJhooaPU/?igshid=us9hjkv
> ```

The link gives a 404 code for me. Can you provide some public reel?

**Comment by Hax4us** [comment]
link edited check again

**Comment by webistomin** [comment]
> link edited check again

Thanks, it works. I'll do it as soon as I can.

**Comment by webistomin** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Can you add support to download instagram Reels

I added a new function. Try to install the `3.1.0` version.

```bash
npm i nanogram@3.1.0
```

### **Get media content by providing instagram reel id**

#### ES2015

```js
import { getMediaByReelId } from 'nanogram.js'

getMediaByReelId('CKONdDkJaPU').then((media) => {
  console.log(media);
});
```

#### CommonJS

```js
const getMediaByReelId = require('nanogram.js').getMediaByReelId;

getMediaByReelId('CKONdDkJaPU').then((media) => {
  console.log(media);
});
```

#### IIFE

```js
const getMediaByReelId = window.Nanogram.getMediaByReelId

getMediaByReelId('CKONdDkJaPU').then((media) => {
  console.log(media);
});
```

_Note_: get content from [reel page](https://www.instagram.com/reel/CKONdDkJaPU/)
