### ISSUE TITLE
XMLHttpRequest not defined

### ISSUE THREAD

**Issue by EhsanFox** [webistomin/nanogram.js#329]
Just Tried the post id example and got this error:
`(node:13776) UnhandledPromiseRejectionWarning: ReferenceError: XMLHttpRequest is not defined`

the first thing I did was to install hmlhttprequest manually with npm, but no changes....

**Comment by webistomin** [comment]
> Just Tried the post id example and got this error:
> `(node:13776) UnhandledPromiseRejectionWarning: ReferenceError: XMLHttpRequest is not defined`
> 
> the first thing I did was to install hmlhttprequest manually with npm, but no changes....

Are you using this library in node.js?

Try

```
const XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

// For versions of node earlier than 12.x, use this globalThis polyfill:
(function() {
  if (typeof globalThis === 'object') return;
  Object.defineProperty(Object.prototype, '__magic__', {
    get: function() {
      return this;
    },
    configurable: true
  });
  __magic__.globalThis = __magic__;
  delete Object.prototype.__magic__;
}());

if (!globalThis.XMLHttpRequest) {
  globalThis.XMLHttpRequest = XMLHttpRequest;
}
```

**Comment by EhsanFox** [comment]
hey, sorry for the late reply,

yes I do use it with using node.js

and I just woke up, add this code to the file, and launched the code for the 1st time, and got this error:
`Error: [nanogram.js] It looks like your network has been temporary banned because of too many requests.`

**Comment by EhsanFox** [comment]
it was the 1st time and it's a little bit confusing!

**Comment by webistomin** [comment]
> it was the 1st time and it's a little bit confusing!

Try this:

```js
const XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
const getMediaByUsername = require('nanogram.js').getMediaByUsername;

(function () {
  if (typeof globalThis === 'object') return;
  Object.defineProperty(Object.prototype, '__magic__', {
    get: function () {
      return this;
    },
    configurable: true,
  });
  __magic__.globalThis = __magic__;
  delete Object.prototype.__magic__;
})();

if (!globalThis.XMLHttpRequest) {
  globalThis.XMLHttpRequest = XMLHttpRequest;
}

getMediaByUsername('instagram').then((media) => {
  console.log(media);
});
```

Does it work for you?

**Comment by EhsanFox** [comment]
it came with the same `Error: [nanogram.js] It looks like your network has been temporary banned because of too many requests.` error!

**Comment by webistomin** [comment]
> it came with the same `Error: [nanogram.js] It looks like your network has been temporary banned because of too many requests.` error!

Seems like Instagram detected bot activity on your end. It works fine for me.

**Comment by EhsanFox** [comment]
However, im gonna try with vpn or even on vps later, thank u!
