### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by Schewns** [webistomin/nanogram.js#402]
It seems that CORS policy is blocking the calls.
Not sure if this can be solved easily in nanogram, but is giving this error even in Nanogram demo page

**Comment by webistomin** [comment]
> It seems that CORS policy is blocking the calls.
> Not sure if this can be solved easily in nanogram, but is giving this error even in Nanogram demo page

Yes, I've already seen it. Instagram stepped up its anti-API bypass policy a couple of weeks ago. Many packages have this problem, so far I don't know a solution for this problem. More precisely, I know that this can be bypassed using a proxy server, but you need node.js. For the browser, I don't know the solution yet.

**Comment by dohomi** [comment]
Is there a solution for the server out? I see  Error: Cross origin http://localhost forbidden trying out this package on NodeJS and inside my test suite

**Comment by webistomin** [comment]
> Is there a solution for the server out? I see `Error: Cross origin http://localhost forbidden` trying out this package on NodeJS and inside my test suite

I managed to bypass CORS via [local-cors-proxy](https://github.com/garmeeh/local-cors-proxy) a couple of weeks ago. Now it gives me error `429`. Seems like they fixed it. Haha.

**Comment by webistomin** [comment]
> Is there a solution for the server out? I see `Error: Cross origin http://localhost forbidden` trying out this package on NodeJS and inside my test suite

Finally made a working solution.

```js
const express = require('express')
const cors = require('cors')
const XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
const getMediaByPostId  = require('nanogram.js').getMediaByPostId ;
const app = express()
const port = 3000

app.use(cors())

if (!globalThis.XMLHttpRequest) {
  globalThis.XMLHttpRequest = XMLHttpRequest;
}

app.get('/', async (req, res) => {
  try {
    const media = await getMediaByPostId('CMrx9CgKFp4');
    res.send(media)
  } catch (error) {
    res.send('Error during request')
  }
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

But some methods still give errors, such as requesting a profile. They redirect me to the login page. The profile page cannot be viewed by unauthorized users. I don't know when this rule was introduced.

**Comment by restyler** [comment]
> They redirect me to the login page. The profile page cannot be viewed by unauthorized users. I don't know when this rule was introduced.

Instagram now allows only clean residential ip addresses to request data from it, no datacenters are allowed. Take a look at https://rapidapi.com/restyler/api/instagram40

**Comment by webistomin** [comment]
@restyler, thank you! I'll take a look at this as soon as I can.

**Comment by facuquilmes123** [comment]
> > > They redirect me to the login page. The profile page cannot be viewed by unauthorized users. I don't know when this rule was introduced.
> > 
> > 
> > Instagram now allows only clean residential ip addresses to request data from it, no datacenters are allowed. Take a look at https://rapidapi.com/restyler/api/instagram40
> 
> That is good. Works as it should. Is it possible to create one on top of `express.js` and host it somewhere on vercel?

Can you make it work?

Thanks a lot !!
