### ISSUE TITLE
Nanogram stopped working (Cannot read property '0' of undefined)

### ISSUE THREAD

**Issue by zwickmueller** [webistomin/nanogram.js#51]
**Describe the bug**
I was just working with this nice library, and after a new reload, it just stopped working. Since I haven't changed my code regarding the library, I took a look at the demo again, and the same error appears there in the console as well: 

`TypeError: Cannot read property '0' of undefined
    at r.<anonymous> (nanogram.iife.min.js:5)
    at nanogram.iife.min.js:5
    at Object.next (nanogram.iife.min.js:5)
    at l (nanogram.iife.min.js:5)`

Just 2 hours ago, the demo was working.

If I would have to guess, I would say that Instagram again changed something (again) in their setup, and since (correct me if I'm wrong) this Library acts more like a crawler, their changes probably broke it.

**To Reproduce**
1. Go to https://nanogram-js.now.sh/
2. Check Console
3. See error

**Desktop (please complete the following information):**
 - Desktop, Chrome, 1.0.2 Version of this library

**Comment by webistomin** [comment]
> **Describe the bug**
> I was just working with this nice library, and after a new reload, it just stopped working. Since I haven't changed my code regarding the library, I took a look at the demo again, and the same error appears there in the console as well:
> 
> `TypeError: Cannot read property '0' of undefined at r.<anonymous> (nanogram.iife.min.js:5) at nanogram.iife.min.js:5 at Object.next (nanogram.iife.min.js:5) at l (nanogram.iife.min.js:5)`
> 
> Just 2 hours ago, the demo was working.
> 
> If I would have to guess, I would say that Instagram again changed something (again) in their setup, and since (correct me if I'm wrong) this Library acts more like a crawler, their changes probably broke it.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to https://nanogram-js.now.sh/
> 2. Check Console
> 3. See error
> 
> **Desktop (please complete the following information):**
> 
> * Desktop, Chrome, 1.0.2 Version of this library

Hello! The demo still works. Perhaps you made a large number of requests in a short period of time. There is a limit.

**Comment by webistomin** [comment]
If the error still occurs, please see the network tab in devtools. Is there an answer from instagram and what is the status code?

**Comment by zwickmueller** [comment]
Hi, thanks for the fast response. I do have a HMR setup going, so I could have potentially reached the limit when working on the site. The thing that is unclear to me though:

a) If I reached the limit on my site, why does the demo also not work for me? Is it a timeout per IP or sth like that? 
b) Both the demo and my site also do not work on my laptop (WLAN, Windows), but it does work on my phone (Same WLAN, but IOS). I haven't worked on the site with my laptop, but the limit seems to apply there too. So:

Do you know how the limit is being enforced by Instagram? Any idea on how long the timeout will last?

Also regarding the Network tab, here a little video: https://imgur.com/a/rAlzy1a 
So status code 301/302

Anyway, thank you for looking into this. Cheers!

**Comment by webistomin** [comment]
@zwickmueller 

I found a couple of articles about ban from instagram. It says:
> Usually, the duration of a temporary Instagram ban ranges from few hours to 24-48 hours. The duration of ban also depends on your follow up actions. If you would continue doing the wrong actions, the ban may prolong.

Perhaps for development it is worth using fake data with a similar data structure. And for production use real data from the library. Any ideas?

**Comment by webistomin** [comment]
Also check out this issue https://github.com/jsanahuja/jquery.instagramFeed/issues/64
Found a similar library. I think the problem is identical

**Comment by zwickmueller** [comment]
Ah alright, thanks for investigating, I appreciate it! Since this is an issue not directly caused by nanogram, i will close this issue. For my project right now, I can wait and/or use fake data in the meantime. But maybe add a section to the readme, so people know why/when this error is happening with the quote you mentioned above.

**Comment by jsanahuja** [comment]
> Also check out this issue [jsanahuja/jquery.instagramFeed#64](https://github.com/jsanahuja/jquery.instagramFeed/issues/64)
> Found a similar library. I think the problem is identical

Probably the same, we did a better analysis here: jsanahuja/jquery.instagramFeed#25
