### ISSUE TITLE
Remove Fetch API

### ISSUE THREAD

**Issue by webistomin** [webistomin/nanogram.js#58]
Replace Fetch with XHR

**Comment by yusufkhan07** [comment]
Hi, can you please tell what's the reason to remove Fetch? And what's the reason to replace it with XHR, and not something like Axios?

**Comment by webistomin** [comment]
> Hi, can you please tell what's the reason to remove Fetch? And what's the reason to replace it with XHR, and not something like Axios?

Fetch does not work in older browsers and requires polyfilling, while XHR is old enough and works everywhere. By rewriting Fetch to XHR, we will get rid of polyfills and will load less javascript code.

Axios is overkill here. Why do we need to load extra 4.4kb of javascript for a couple of requests?

**Comment by yusufkhan07** [comment]
I understand your point, but XHR isn't available in the nodejs environment.
How about using a fetch polyfill?

**Comment by webistomin** [comment]
> I understand your point, but XHR isn't available in the nodejs environment.
> How about using a fetch polyfill?

As far as I know, there is neither fetch nor XHR in node.js. You will have to load the polyfill anyway.
But if we replace fetch with XHR, we will help the user of the client JS. Let's save them from polyfills.

**Comment by yusufkhan07** [comment]
Ohh ok thank you; so for replacing fetch with XHR, we'll have to update the tests as well because they're using fetch mocks for testing, correct?

**Comment by webistomin** [comment]
Yes, there is a lot of work. Do you want to help? 😊

**Comment by yusufkhan07** [comment]
Already working on it :)

**Comment by yusufkhan07** [comment]
Do we need to update the tests though? Tests are supposed to test the functionality of the system, by replacing fetch with XHR, we aren't changing any functionality of the system so I think we can keep the existing test suite.

**Comment by yusufkhan07** [comment]
Here's the progress:
https://github.com/yusufkhan07/nanogram.js/commits/feature/xhr-migration

I'll make a pull request soon, let me know if something can be improved :)

**Comment by yusufkhan07** [comment]
Running `npm run build:all` is fine but when I run `npm run build`, all the docs are updated and your git username is replaced with mine. Is this the desired behaviour, or shall I either commit the dist files generated with `npm run build:all` or should I just excluded the docs folder from the commit?

**Comment by webistomin** [comment]
> Running `npm run build:all` is fine but when I run `npm run build`, all the docs are updated and your git username is replaced with mine. Is this the desired behaviour, or shall I either commit the dist files generated with `npm run build:all` or should I just excluded the docs folder from the commit?

Better to exclude. I will rebuild myself
