### ISSUE TITLE
Unable to commit anything in the repo due to husky failure

### ISSUE THREAD

**Issue by yusufkhan07** [webistomin/nanogram.js#91]
**Describe the bug**
I cloned the repository and made a few changes in the code. I've installed all the dependencies.
I'm able to stage code changes in git but when I execute `git commit`, I get the following output:

```
↓ Skipped because of errors from tasks. [SKIPPED]   
                                                                                                                                                                                    
other:eslint:write failed without output (ENOENT).                                                                  
husky > pre-commit hook failed (add --no-verify to bypass)   
```
It seems like lint-staged is unable to find the task `other:eslint:write`. 

**To Reproduce**
1. Clone the repo.
2. Install dependencies using `npm i`
3. Edit code.
4. Git Add .
5. Git commit -m "Some commit message"

**Expected behavior**
lint-stage is already setup in the project so it should be able to find the tasks mentioned in the config file.

**Comment by yusufkhan07** [comment]
I am able to fix the issue by changing the tasks in lint-stage from 
```
module.exports = {
  'src/**/*.ts': ['other:eslint:write', 'other:prettier:write', 'npx scriptlint', 'git add'],
};

```
to
```
module.exports = {
  'src/**/*.ts': ['npm run other:eslint:write', 'npm run other:prettier:write', 'npx scriptlint', 'git add'],
};

```

I'm working on adding a new feature to the repository, I am unsure if I should commit this change as well.

**Comment by webistomin** [comment]
> I am able to fix the issue by changing the tasks in lint-stage from
> 
> ```
> module.exports = {
>   'src/**/*.ts': ['other:eslint:write', 'other:prettier:write', 'npx scriptlint', 'git add'],
> };
> ```
> 
> to
> 
> ```
> module.exports = {
>   'src/**/*.ts': ['npm run other:eslint:write', 'npm run other:prettier:write', 'npx scriptlint', 'git add'],
> };
> ```
> 
> [yusufkhan07@f6cacce](https://github.com/yusufkhan07/nanogram.js/commit/f6cacce16f4baa72fff400077e25ba9a5f7412a8)
> 
> I'm working on adding a new feature to the repository, I am unsure if I should commit this change as well.

I saw you commit it. It's fine. Thanks😊
